services:
  backend:
    volumes:
      - ./backend:/app    
    environment:
      - FLASK_ENV=development
      - FLASK_APP=scripts/app.py
    command: flask run --host=0.0.0.0 --port=5000 --reload

  frontend:
    volumes:
      - ./client:/app     
      - /app/node_modules  
    command: npm run dev


